<?php
/** @package CanisDatabase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ClienteMap.php");

/**
 * ClienteDAO provides object-oriented access to the cliente table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package CanisDatabase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ClienteDAO extends Phreezable
{
	/** @var string */
	public $Nomeusuario;

	/** @var string */
	public $Sobrenomeusuario;

	/** @var string */
	public $Telefoneusuario;

	/** @var string */
	public $Cpfusuario;

	/** @var string */
	public $Usuario;

	/** @var string */
	public $Senha;

	/** @var char */
	public $Cepusuario;

	/** @var string */
	public $Estadousuario;

	/** @var string */
	public $Cidadeusuario;

	/** @var string */
	public $Bairrousuario;

	/** @var string */
	public $Logradourousuario;

	/** @var string */
	public $Numerousuario;

	/** @var blob */
	public $Imagem;


	/**
	 * Returns a dataset of Pedidos objects with matching Cpfusuario
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCpfusuarioPedidoss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_cpfUsuario", $criteria);
	}


}
?>